### ISSUE TITLE
[1][QA Testing] Read and load maze from file

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#10]
QA Test cases for #2 and the results

**Comment by gabriel-lau** [comment]
Test Cases and results found in #25

**Comment by janinedesiree** [comment]
Round 1 of testing was complete, with 2 errors found. @halfofning has made the changes, which will be done in Round 2 of testing.

![image](https://user-images.githubusercontent.com/44887189/74044042-65b6eb80-4a05-11ea-8c44-ab68afe40ab9.png)

**Comment by janinedesiree** [comment]
Final testing complete! References issue #34 has been resolved.

![image](https://user-images.githubusercontent.com/44887189/74105121-0d632380-4b96-11ea-9c3c-45499c9c3621.png)
