### ISSUE TITLE
[2][QA Testing] View maze

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#11]
QA Test cases for #3 and the results

**Comment by gabriel-lau** [comment]
Test Cases and results found in #26

**Comment by janinedesiree** [comment]
Testing for these have been complete. Clarified on expected outcome for TC01 with @halfofning and found it is behaving as expected.

![image](https://user-images.githubusercontent.com/44887189/74044433-05747980-4a06-11ea-846f-b002694b0702.png)
