### ISSUE TITLE
[3][QA Testing] Play maze game

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#12]
QA Test cases for #4 and the results

**Comment by janinedesiree** [comment]
Manual testing for this has been completed! Below are the results:
![image](https://user-images.githubusercontent.com/44887189/74051989-04e2df80-4a14-11ea-89c7-e35f9aaa96e1.png)
![image](https://user-images.githubusercontent.com/44887189/74052028-1cba6380-4a14-11ea-925b-e524f73adbfc.png)

**Comment by janinedesiree** [comment]
Final round of testing completed! Referenced issues #37 and #38  have been resolved.

![image](https://user-images.githubusercontent.com/44887189/74105043-64b4c400-4b95-11ea-8bb6-2266efd3851b.png)
![image](https://user-images.githubusercontent.com/44887189/74105052-71d1b300-4b95-11ea-9fef-cd47a2ebcd65.png)
