### ISSUE TITLE
[4][QA Testing] Configure current maze

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#13]
QA Test cases for #5 and the results

**Comment by janinedesiree** [comment]
Documentation can be found here #36

**Comment by gabriel-lau** [comment]
![Configure maze test cases new_page-0001](https://user-images.githubusercontent.com/40619564/74079381-a3515e00-4a71-11ea-831f-dd23ae2235d9.jpg)
![Configure maze test cases new_page-0002](https://user-images.githubusercontent.com/40619564/74079390-bfed9600-4a71-11ea-9ae8-8a76c1df3bd7.jpg)
![Configure maze test cases new_page-0003](https://user-images.githubusercontent.com/40619564/74079391-c419b380-4a71-11ea-8ef4-cdcd53202ac2.jpg)
![Configure maze test cases new_page-0004](https://user-images.githubusercontent.com/40619564/74079392-c54ae080-4a71-11ea-870f-4591d500c0b4.jpg)
