### ISSUE TITLE
[5] Display main menu

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#15]
**Description**
Display the main menu and option upon start-up

Dev Test Case: #17
QA Test Case: #16

**Comment by halfofning** [comment]
### Tech Spec
<img width="522" alt="Screenshot 2020-01-29 at 6 04 07 PM" src="https://user-images.githubusercontent.com/28654855/73386389-b9407f80-4309-11ea-87a0-8c32df1e5880.png">

**Display Menu**
- [x] Display menu text
- [x] Prompt user for input -> Check for special characters and strings 
  - [x] Options 1 - 4: Calls respective functions
  - [x] Invalid input; display error message ("Invalid option. Please try again!")
  - [x] Option 0: Break out of loop, display "Thanks for playing Maze!" message 

**Note: While loop*

**Comment by halfofning** [comment]
Merged @ #20, but error found when running `main(maze_list)` with unit tests - Need to check for mocking values using tests. 

Works fine when running main.py alone. Will be looking into this issue with devs @hsiaojietng & @YUNT3NG.

**Comment by halfofning** [comment]
> Merged @ #20, but error found when running `main(maze_list)` with unit tests - Need to check for mocking values using tests.
> 
> Works fine when running main.py alone. Will be looking into this issue with devs @hsiaojietng & @YUNT3NG.

Will not be looking further into this issue.

**Comment by halfofning** [comment]
<img width="682" alt="Screenshot 2020-02-02 at 4 19 33 PM" src="https://user-images.githubusercontent.com/28654855/73605319-d1e5b980-45d7-11ea-8813-5376d72ffb8f.png">

All tests passed, check #16 for unit test documentation.

Issue closed until QA tests begin & problems arise.
