### ISSUE TITLE
[1] Read and load maze from file

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#2]
**Description:**
Create, Load and read the maze at the start of the program

**Criteria:**
- Create two map files of different sizes
- Map has to be located in the MazeFolder
- Map loaded has to be in a nested list for continuity in other options

Dev Test Case: #6 
QA Test Case: #10

**Comment by halfofning** [comment]
### Tech Spec
<img width="377" alt="Screenshot 2020-01-29 at 6 09 24 PM" src="https://user-images.githubusercontent.com/28654855/73347747-16fda900-42c3-11ea-859e-4c3945351a57.png">

**Option 1** - Read and load maze from file
- [x] Create map files in .csv format
- [x] Prompt user for name of data file
  - [x] Only allow .csv files to be read
  - [x] Store map file as a nested list
  - [x] Display number of lines (or list items in list)
- [x] Store start (A) and end (B) location (in terms of row and column number)

**Comment by halfofning** [comment]
Merged @ #20.

**Comment by halfofning** [comment]
<img width="682" alt="Screenshot 2020-02-02 at 4 19 33 PM" src="https://user-images.githubusercontent.com/28654855/73605319-d1e5b980-45d7-11ea-8813-5376d72ffb8f.png">

All tests passed, check #6 for unit test documentation.

Issue closed until QA tests begin & problems arise.
