### ISSUE TITLE
[2][QA Test Cases] View maze

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#26]
Documentation of test cases for option 2, **View maze**

**Comment by janinedesiree** [comment]
**TC01- test_CanViewMaze**

**Passing/Failing?:** Passing

**Test Description:**
This is to test that users are able to view a maze that has been successfully loaded

**Preconditions:**
Load in maze.csv file via Option 1 first

**Test Steps:**
1. Choose option 3

**Expected Results:**
Maze is successfully loaded and displayed

**Actual Results:**

——————
**TC02- test_CannotViewMaze**

**Passing/Failing?:** Failing

**Test Description:**
This is to test that users are unable to view any maze if none has been loaded

**Preconditions:**
Ensure no files have been loaded

**Test Steps:**
1. Choose option 3

**Expected Results:**
"No maze” error message displayed

**Actual Results:**

——————

**Comment by janinedesiree** [comment]
@gabriel-lau @halfofning Finished manual testing, TC01 failed. Maze was successfully loaded, but no confirmation message to indicate this.

**Comment by halfofning** [comment]
@janinedesiree TC01 behaving as expected! Thanks for the check! 👍See issue #29 for extra details.

**Comment by janinedesiree** [comment]
Modified TC01 after confirming behaviour with Tech Lead
