### ISSUE TITLE
[1 - TC03] Python error when users upload non-csv file

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#27]
#25 TC03 - Test case failed. Program ends abruptly with python error messages displayed

**Comment by halfofning** [comment]
Behaving as expected. Thanks for the check!

<img width="284" alt="Screenshot 2020-02-05 at 11 26 57 PM" src="https://user-images.githubusercontent.com/28654855/73855403-01622380-486f-11ea-9ff7-b9c3a3c313a9.png">

**Comment by janinedesiree** [comment]
@halfofning noted on this, thanks!
