### ISSUE TITLE
[1 - TC02] Python error when users upload a .csv file that cannot be found

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#28]
#25 TC02 failed. Program quits and python error messages get displayed

**Comment by halfofning** [comment]
Added a fix for this error at PR #30. @janinedesiree please check & merge if okay! Thanks! 💯

**Comment by janinedesiree** [comment]
@halfofning error seems to continue to break the program if file cannot be found. Should an error message be displayed instead to try again instead of having the program break abruptly?

![image](https://user-images.githubusercontent.com/44887189/74049261-ba129900-4a0e-11ea-882b-c5bf5490a220.png)

**Comment by halfofning** [comment]
@janinedesiree try pulling from the `upload-non-csv` branch and try again, thanks!
