### ISSUE TITLE
[2] View maze

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#3]
**Description:**
Viewing the maze after loading the csv file from the first option

Dev Test Case: #7 
QA Test Case: #11

**Comment by halfofning** [comment]
### Tech Spec
<img width="364" alt="Screenshot 2020-01-29 at 6 18 13 PM" src="https://user-images.githubusercontent.com/28654855/73348087-b9b62780-42c3-11ea-8d3e-0f8ed7816105.png">

**Option 2** - View maze
- [x] Print nested lists that were stored in variable (e.g. mazeList), separated with a new line

**Comment by halfofning** [comment]
Merged @ #20.

**Comment by halfofning** [comment]
<img width="682" alt="Screenshot 2020-02-02 at 4 19 33 PM" src="https://user-images.githubusercontent.com/28654855/73605319-d1e5b980-45d7-11ea-8813-5376d72ffb8f.png">

All tests passed, check #7 for unit test documentation.

Issue closed until QA tests begin & problems arise.
