### ISSUE TITLE
[1 - TC01] Error when users uploads existing csv file

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#34]
#10 - TC01 - Uploading of existing .csv file leads to program stopping

@halfofning maze.csv file is located outside of SRC folder where the main program resides. This error occurs when the input is "maze.csv"

<img width="569" alt="Screenshot 2020-02-07 at 11 07 33 PM" src="https://user-images.githubusercontent.com/44887189/74040558-e58d8780-49fe-11ea-9d29-3f1a94e5f2ef.png">

I noticed that the file gets uploaded if the full pathname is inserted, or if ../maze.csv is the input. May not be the most user-friendly approach.

**Comment by halfofning** [comment]
<img width="208" alt="Screenshot 2020-02-08 at 1 45 38 AM" src="https://user-images.githubusercontent.com/28654855/74052374-b5e97a00-4a14-11ea-9cf2-e42623ea7705.png">

**Comment by janinedesiree** [comment]
![image](https://user-images.githubusercontent.com/44887189/74053257-61df9500-4a16-11ea-8324-e2b66c228793.png)

**Comment by halfofning** [comment]
Not fixing this bug!
