### ISSUE TITLE
[3][TC01-5 to TC01-8] “Invalid character” message is displayed for lowercase input

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#37]
#12 TC01-5 to TC01-8 full test results
![image](https://user-images.githubusercontent.com/44887189/74052557-1678b700-4a15-11ea-942c-6672af6a7973.png)

User is able to traverse through maze using uppercase WSAD, but an error occurs when using lowercase wsad. Please take a look! @halfofning

**Comment by halfofning** [comment]
Assigned to @YUNT3NG. Please fix to allow input of lowercase characters.

**Comment by gabriel-lau** [comment]
Fixed already, nice!
