### ISSUE TITLE
[3][TC06] Program ends when user finishes maze

### ISSUE THREAD

**Issue by janinedesiree** [gabriel-lau/Project_Kavala#38]
#12 TC06 full test results!

![image](https://user-images.githubusercontent.com/44887189/74052822-9141d200-4a15-11ea-9086-847981952693.png)

@halfofning  -the program ends abruptly when the user finishes the maze instead of being brought back to the main menu.

**Comment by halfofning** [comment]
@YUNT3NG please take a look!

**Comment by gabriel-lau** [comment]
Fixed already, nice!
