### ISSUE TITLE
[4 - TC02] Error when user chooses option 4 without choosing csv file

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#39]
#13 - TC02 - User is shown an error message but is not redirected accordingly

![TC2](https://user-images.githubusercontent.com/40619564/74079465-da743f00-4a72-11ea-93c4-8424735fe5c0.png)

**Comment by halfofning** [comment]
@hsiaojietng Please take a look!

**Comment by hsiaojietng** [comment]
Please make sure to uncomment main(maze_list) in certain functions as well as a line called configure(maze_list) when manually testing because of the request for input, it fails the pytest, thus it is required to be commented out when pytesting

**Comment by gabriel-lau** [comment]
Different error is shown in #47 

![TC02](https://user-images.githubusercontent.com/40619564/74087602-e8ed4580-4ac8-11ea-86a8-c4ce9767db14.png)

**Comment by hsiaojietng** [comment]
Please have a look again, I have fixed it @gabriel-lau

**Comment by gabriel-lau** [comment]
Alright it works now, thanks
