### ISSUE TITLE
[3] Play maze game

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#4]
**Description:**
Playing the maze game after loading the selected csv maze map and reading from the nested list

Dev Test Case: #8 
QA Test Case: #12

**Comment by halfofning** [comment]
### Tech Spec
<img width="480" alt="Screenshot 2020-01-29 at 6 26 51 PM" src="https://user-images.githubusercontent.com/28654855/73348765-f20a3580-42c4-11ea-817d-31f0f46f2f81.png">

**Option 3** - Play maze game
- [x] Display maze from list (maze_list)
- [x] Display location of Start (A) and End (B), previously stored in variables: `row_A, column_A, row_B, column_B`
- [x] Prompt user to enter characters: `W`, `A`, `S`, `D`, `M`
  - [x] Check if valid characters are entered; else display error message at the bottom.

------
- [x] Check if there is a PATH (O) to move up/right/left/down
  - [x] If there's a PATH (O), move the START 'A' character one space up/right/left/down
<img width="318" alt="Screenshot 2020-01-29 at 6 39 10 PM" src="https://user-images.githubusercontent.com/28654855/73349805-d0aa4900-42c6-11ea-9bd1-470c568caa59.png">

  - [x] If NO PATH (X), display message ('Invalid movement. Please try again.") at the bottom.
<img width="590" alt="Screenshot 2020-01-29 at 6 37 37 PM" src="https://user-images.githubusercontent.com/28654855/73349798-cd16c200-42c6-11ea-98de-8f7d84ea04d1.png">

------
- [x] Check if the Start (A) has reached the End (B)
  - [x] When `row_A == row_B && column_A == column_B`, display victory message at the bottom
  - [ ] Suggestion: Set a boolean flag `victory`

- [x] Loop display maze & show the new position of the START point (`row_A, column_A`) and END point (`row_B, column_B`)
  - [x] Quit if the 'M' character is entered to exit to main menu
  - [x] Quit if game has ended (`victory == True`)
  - [x] Else, continue looping the game
