### ISSUE TITLE
[4 - TC03] Maze not shown when option 4 is chosen

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#40]
#13 - TC03 - Option works properly, but the maze is not shown as shown and specified in the assignment docs
![TC3](https://user-images.githubusercontent.com/40619564/74079499-553d5a00-4a73-11ea-9af8-8606dde52161.png)

**Comment by halfofning** [comment]
@gabriel-lau Thanks. Please provide steps taken to replicate this error!
@hsiaojietng Please take a look.

**Comment by hsiaojietng** [comment]
I have included the displaying of the maze list before showing the configuration menu.

**Comment by gabriel-lau** [comment]
Yup issue is fixed in #47
