### ISSUE TITLE
[4 - TC07] Invalid error handling when false values entered as coordinates

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#41]
#13 - TC07 - User sent back to the main menu after "A" is entered as coordinates after a feature is chosen from the configuration menu

![TC7](https://user-images.githubusercontent.com/40619564/74079542-c5e47680-4a73-11ea-9a75-0c938c916505.png)

**Comment by halfofning** [comment]
@hsiaojietng please take a look!

**Comment by hsiaojietng** [comment]
Included error handling when invalid option is inputted for this particular scenario.

**Comment by gabriel-lau** [comment]
Different error is shown in #47 

![TC07](https://user-images.githubusercontent.com/40619564/74087595-da069300-4ac8-11ea-96eb-7dd7b705d6bb.png)

**Comment by hsiaojietng** [comment]
Please review again, I have fixed it @gabriel-lau

**Comment by gabriel-lau** [comment]
Alright it works now, thanks
