### ISSUE TITLE
[4 - TC08] Out of range coordinates not handled  

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#42]
#13 - TC08 - Entering an out of range coordinate (100,100) in any of the features replaces the top right space

![TC8](https://user-images.githubusercontent.com/40619564/74079594-8702f080-4a74-11ea-8551-6d4423422eb0.png)

**Comment by halfofning** [comment]
@hsiaojietng Please take a look!

**Comment by hsiaojietng** [comment]
Fixed this issue.

**Comment by gabriel-lau** [comment]
Issue is fixed in #47
