### ISSUE TITLE
[4 - TC09] User not redirected accordingly

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#43]
#13 - TC09 - The user is redirected to the main menu page despite entering "B" to be redirected to the configuration menu

![TC9](https://user-images.githubusercontent.com/40619564/74079605-c9c4c880-4a74-11ea-99e9-350a848771a9.png)

**Comment by hsiaojietng** [comment]
Made necessary changes to this such that Configuration menu is shown instead. Please take note to comment out main(maze_list) in [4] 1 Display Configure maze menu, [4] 3 Exit Config menu, [4] 5 Return to Main menu as well as configure_maze(maze_list) in [4] 4 Return to config menu for pytest to pass.

**Comment by gabriel-lau** [comment]
A different Error is shown in #47 

![TC09](https://user-images.githubusercontent.com/40619564/74087584-c529ff80-4ac8-11ea-8792-0d1bf8a3f312.png)

**Comment by hsiaojietng** [comment]
Fixed issues again, please check again

**Comment by gabriel-lau** [comment]
Alright it works now, thanks
