### ISSUE TITLE
[4] Configure current maze

### ISSUE THREAD

**Issue by gabriel-lau** [gabriel-lau/Project_Kavala#5]
**Description**
Configuring the maze selected in the first option, updating the walls, passageways, start and endpoints

**Criteria:**
- Update the csv file at the end of the configuration

Dev Test Case: #9 
QA Test Case:  #13

**Comment by halfofning** [comment]
### Tech Spec
<img width="433" alt="Screenshot 2020-01-29 at 7 11 47 PM" src="https://user-images.githubusercontent.com/28654855/73352040-37316600-42cb-11ea-9148-b0a5460033cd.png">

**Option 4** - Configure current maze
- [x] Prompt user to select option
  - [x] Prompt user to enter coordinates `(row, column)`
  - [x] If user enters `B` - Return to configure menu
  - [x] If user enters `M` - Return to main menu 

**Note: Nested Loops*

<img width="408" alt="Screenshot 2020-01-29 at 7 11 05 PM" src="https://user-images.githubusercontent.com/28654855/73351997-2123a580-42cb-11ea-9c51-34a4f957e442.png">

- [x] Create wall (X)
  - [ ] Check if selected `(row, column)` coincide with Start (A) or End (B); display error message
- [x] Create passageway (O)
  - [ ] Check if selected `(row, column)` coincide with Start (A) or End (B); display error message
- [x] Create start point (A)
  - [ ] Check if selected `(row, column)` coincide with Start (A) or End (B); display error message
- [x] Create end point (B)
  - [ ] Check if selected `(row, column)` coincide with Start (A) or End (B); display error message
